### ISSUE TITLE
GFG POTD - Sub-arrays with equal number of occurrences (DATE: 22-10-2024)

### ISSUE THREAD

**Issue by MeenakshiAM** [Gyanthakur/GFG_POTD#197]
## 📝 Description

Solving Sub-arrays with equal number of occurrences
Difficulty: Hard
Given an array arr[] and two integers say, x and y, find the number of sub-arrays in which the number of occurrences of x is equal to the number of occurrences of y.

## 🌐 Additional Context
Please assign this to me under hackatoberfest-2024

**Comment by Gyanthakur** [comment]
#198
