### ISSUE TITLE
Add gfg potd 

### ISSUE THREAD

**Issue by Gyanthakur** [Gyanthakur/GFG_POTD#8]

**Comment by shreerajbhamare** [comment]
Please assign it to me, Happy to contribute

**Comment by Gyanthakur** [comment]
> Please assign it to me, Happy to contribute

read carefully about how to contribute and follow each step

**Comment by harsh0728** [comment]
Please assign this to me i can add gfg potd as i solved daily gfg potd. I will be happy to contribute to your codebase

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/ @Gyanthakur

**Comment by Samruddhi345A** [comment]
please assign me this task

**Comment by rko0211** [comment]
please assign me

**Comment by Salonisaroha** [comment]
please assign this issue to me @Gyanthakur
